Repository KEA-ChunSam/PlayUs-AI, pull requests merged in 2025-06, with the labels that each got.

#24 CS-371 Fix/토큰 전달 방식 변경
  main.py
  utils/jwt.py
Labels: 🐛 bug, 예찬

#28 챗봇 성능 개선(일정)
  Utilities에서
  chat/chat_bot.py
  main.py
Labels: ♻️ refactor, AI

#30 챗봇 성능 개선
  chat/chat_bot.py
Labels: AI
